title: Snowflake Foundations
remote_theme: just-the-docs/just-the-docs

url: https://office-of-data-and-efficiency.github.io/snowflake_foundations/

search_enabled: true

heading_anchors: true

toc:
  enabled: true